/* eslint-disable no-undef */
const URL = 'http://localhost:8080/#/students/'

describe('Manage Students page', () => {
  beforeEach(() => {
    cy.visit('http://localhost:8080/#/login')
    cy.get('label')
      .contains('Username')
      .next()
      .type('admin')
    cy.get('input[data-test=password]')
      .type('11')
    cy.get('button[type=submit]').click()
    cy.wait(1000)
    cy.url()
      .should('include', 'http://localhost:8080/#/')
    cy.request('https://assignment2-prod.herokuapp.com/students/')
      .its('body')
      .then(students => {
        console.log(students)
        students.forEach(element => {
          cy.request('DELETE', `${'https://assignment2-prod.herokuapp.com/students/'}${element._id}`)
        })
      })
    cy.fixture('students').then(students => {
      // eslint-disable-next-line no-unused-vars
      let [d1, d2, d3, d4, ...rest] = students
      let four = [d1, d2, d3, d4]
      four.forEach(student => {
        cy.request('POST', `${'https://assignment2-prod.herokuapp.com/students/'}`, student)
      })
    })
    cy.visit(URL)
  })
  describe('Delete operation', () => {
    it('reduces the no. of students by 1', () => {
      cy.get('tbody')
        .find('tr')
        .should('have.length', 4)
      // Click trash/delete link of 3rd donation in list
      cy.get('tbody')
        .find('tr')
        .eq(2)
        .find('td')
        .eq(10)
        .find('a')
        .click()
      cy.get('.wc-popup-button')
        .contains('OK')
        .click()
      cy.get('tbody')
        .find('tr')
        .should('have.length', 3)
    })
  })
  describe('Edit operation', () => {
    it('edit the student successfully', () => {
      cy.wait(1000)
      cy.get('tbody')
        .find('tr')
        .eq(2)
        .find('td')
        .eq(9)
        .find('a')
        .click()
      cy.wait(1000)
      cy.url()
        .should('include', 'edit')
      cy.get('label')
        .contains('Age')
        .next()
        .clear()
        .type('20')
      cy.get('button[type=submit]').click()
      cy.contains('Success').should('exist')
      cy.get(':nth-child(8) > .btn').click()
      cy.url().should('include', '/students')
      cy.get('tbody')
        .find('tr')
        .should('have.length', 4)
      cy.get(':nth-child(3) > :nth-child(3)')
        .contains(20)
      it('edit s student with error', () => {
        cy.get('label')
          .contains('Age')
          .next()
          .type('2')
        cy.get('.error').contains('Age')
          .should('exist')
        cy.get('label')
          .contains('Name')
          .next()
          .clear()
          .type('A')
        cy.get('.error').contains('Name')
          .should('exist')
        cy.get('label')
          .contains('Age')
          .next()
          .clear()
        cy.get('.error').contains('required')
          .should('exist')
        cy.get('label')
          .contains('Name')
          .next()
          .clear()
        cy.get('.error').contains('required')
          .should('exist')
        cy.get('button[type=submit]').click()
        cy.contains('Try').should('exist')
      })
    })
  })

  describe('Upvote operation', () => {
    it('upvote the student by 1', () => {
      cy.get('tbody')
        .find('tr')
        .should('have.length', 4)
      // Click trash/delete link of 3rd donation in list
      cy.get('tbody')
        .find('tr')
        .eq(2)
        .find('td')
        .eq(8)
        .find('a')
        .click()
      cy.get(':nth-child(3) > :nth-child(8)').contains('1')
      // cy.get(':nth-child(1) > :nth-child(9) > .fa')
      //   .click()
      // cy.wait(1000)
      // cy.get('tbody')
      //   .find('tr')
      //   .should('have.length', 3)
    })
  })
})
