/* eslint-disable no-undef */
const URL = 'http://localhost:8080/#/teachers/'

describe('Manage Teachers page', () => {
  beforeEach(() => {
    cy.visit('http://localhost:8080/#/login')
    cy.get('label')
      .contains('Username')
      .next()
      .type('admin')
    cy.get('input[data-test=password]')
      .type('11')
    cy.get('button[type=submit]').click()
    cy.wait(1000)
    cy.url()
      .should('include', 'http://localhost:8080/#/')
    cy.request('https://assignment2-prod.herokuapp.com/teachers/')
      .its('body')
      .then(teachers => {
        console.log(teachers)
        teachers.forEach(element => {
          cy.request('DELETE', `${'https://assignment2-prod.herokuapp.com/teachers/'}${element._id}`)
        })
      })
    cy.fixture('teachers').then(teachers => {
      // eslint-disable-next-line no-unused-vars
      let [d1, d2, d3, d4, ...rest] = teachers
      let four = [d1, d2, d3, d4]
      four.forEach(teacher => {
        cy.request('POST', `${'https://assignment2-prod.herokuapp.com/teachers/'}`, teacher)
      })
    })
    cy.visit(URL)
  })

  describe('Delete operation', () => {
    it('reduces the no. of teachers by 1', () => {
      cy.get('tbody')
        .find('tr')
        .should('have.length', 4)
      // Click trash/delete link of 3rd donation in list
      cy.get('tbody')
        .find('tr')
        .eq(2)
        .find('td')
        .eq(10)
        .find('a')
        .click()
      cy.get('.wc-popup-button')
        .contains('OK')
        .click()
      cy.get('tbody')
        .find('tr')
        .should('have.length', 3)
    })
  })

  describe('Edit operation', () => {
    it('edit the teacher successfully', () => {
      cy.wait(1000)
      cy.get('tbody')
        .find('tr')
        .eq(2)
        .find('td')
        .eq(9)
        .find('a')
        .click()
      cy.wait(500)
      cy.url()
        .should('include', 'edit')
      cy.get('label')
        .contains('Age')
        .next()
        .clear()
        .type('28')
      cy.get('button[type=submit]').click()
      cy.contains('Success').should('exist')
      cy.get(':nth-child(8) > .btn').click()
      cy.url().should('include', '/teachers')
      cy.get('tbody')
        .find('tr')
        .should('have.length', 4)
      cy.get(':nth-child(3) > :nth-child(3)')
        .contains(28)
      it('edit s teacher with error', () => {
        cy.get('label')
          .contains('Age')
          .next()
          .type('2')
        cy.get('.error').contains('Age')
          .should('exist')
        cy.get('label')
          .contains('Name')
          .next()
          .clear()
          .type('A')
        cy.get('.error').contains('Name')
          .should('exist')
        cy.get('label')
          .contains('Age')
          .next()
          .clear()
        cy.get('.error').contains('required')
          .should('exist')
        cy.get('label')
          .contains('Name')
          .next()
          .clear()
        cy.get('.error').contains('required')
          .should('exist')
        cy.get('button[type=submit]').click()
        cy.contains('Try').should('exist')
      })
    })
  })

  describe('Upvote operation', () => {
    it('upvote the teacher by 1', () => {
      cy.get('tbody')
        .find('tr')
        .should('have.length', 4)
      // Click trash/delete link of 3rd donation in list
      cy.get('tbody')
        .find('tr')
        .eq(2)
        .find('td')
        .eq(8)
        .find('a')
        .click()
      cy.get(':nth-child(3) > :nth-child(8)').contains('1')
    })
  })
})
